"""Work orders — CMMS-lite, per PLAN.md §5.6. An alarm can spawn one ("button on an
alarm -> create a work order"); a small preventive-maintenance list is seeded at
startup rather than built on a real scheduler — a deliberate simplification, not an
oversight. See docs/alarm-engine-notes.md.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Literal

WorkOrderStatus = Literal["open", "in_progress", "done"]


@dataclass
class WorkOrder:
    id: int
    asset: str
    problem: str
    priority: int
    status: WorkOrderStatus
    notes: str
    created_at: datetime
    source_alarm_id: int | None = None


class WorkOrderNotFound(KeyError):
    pass


class WorkOrderStore:
    def __init__(self) -> None:
        self._work_orders: list[WorkOrder] = []
        self._next_id = 1

    def all(self) -> list[WorkOrder]:
        return list(self._work_orders)

    def get(self, work_order_id: int) -> WorkOrder:
        for wo in self._work_orders:
            if wo.id == work_order_id:
                return wo
        raise WorkOrderNotFound(work_order_id)

    def create(
        self,
        asset: str,
        problem: str,
        priority: int,
        now: datetime,
        notes: str = "",
        source_alarm_id: int | None = None,
    ) -> WorkOrder:
        wo = WorkOrder(
            id=self._next_id,
            asset=asset,
            problem=problem,
            priority=priority,
            status="open",
            notes=notes,
            created_at=now,
            source_alarm_id=source_alarm_id,
        )
        self._next_id += 1
        self._work_orders.append(wo)
        return wo

    def set_status(self, work_order_id: int, status: WorkOrderStatus) -> WorkOrder:
        wo = self.get(work_order_id)
        wo.status = status
        return wo


# Per PLAN.md §5.6: "filter change every 90 days, fire alarm annual inspection" — seeded
# once at gateway startup rather than generated by a real recurrence scheduler.
def seed_preventive_maintenance(store: WorkOrderStore, now: datetime) -> None:
    store.create(
        asset="ahu-1",
        problem="90-day filter change due",
        priority=4,
        now=now,
        notes="Preventive maintenance — seeded at startup, not scheduler-generated.",
    )
    store.create(
        asset="fire-panel",
        problem="Annual inspection (CAN/ULC-S536)",
        priority=3,
        now=now,
        notes="Preventive maintenance — seeded at startup, not scheduler-generated.",
    )
